### ISSUE TITLE
Help needed how to model

### ISSUE THREAD

**Issue by gruijter** [Ivordir/YALPS#2]
Hi @Ivordir (or others!). I'm new to Linear Solvers, and I need help modeling a simple battery charging scheme. To understand how it works I built a model that doesn't make sense in the real world, but it should help me understand why it doesn't work right now.

So I want to maximize the cost for charging a battery, and am looking for the optimum charge speed and discharge speed
The cost function that needs to be maximized is:

`totalCost = 0.5*cs - 0.3*ds` (where cs is charge speed, and ds is discharge speed)

There is a constraint for how full the battery can be loaded:
`SoC must stay between 0 and 5`
the SoC is calculated as a function from charge speed and discharge speed:
`SoC = 2*cs - 1.5*ds`

```
{
  direction: 'maximize',
  objective: 'totalCost',
  constraints: { SoC: { min: 0, max: 5 } },
  variables: {
    totalCost: { cs: 0.5, ds: -0.3 },
    SoC: { cs: 2, ds: -1.5 }
  }
}
{ status: 'optimal', result: -0, variables: [] }
```

So when running the model, I would expect that the maximum cost is where the battery is loaded to its maximum capacity. That would be where ds = 0 and cs = 5 / 2 = 2.5. The totalCost would then be 2.5 * 0.5 = 1.25

But as you can see I get result:-0 and no variables. What is wrong in my model? How do I get the expected result?

**Comment by Ivordir** [comment]
Hi @gruijter, sorry for the late response -- I missed your issue.

This should be a simple fix. Rather than specifying the equations (row-wise), YALPS works by taking in variables (column-wise) (this API was inherited from js-lp-solver). So, you just need to "transpose" `variables` like this:
```typescript
{
  direction: 'maximize',
  objective: 'totalCost',
  constraints: { SoC: { min: 0, max: 5 } },
  variables: {
    cs: {
      totalCost: 0.5,
      SoC: 2
    },
    ds: {
      totalCost: -0.3,
      SoC: -1.5
    }
  }
}
/*
{
  status: 'unbounded',
  result: Infinity,
  variables: [ [ 'ds', Infinity ] ]
}
*/
```
Note that this model gives a result of `Infinity`, since for each additional `1 cs`, you can also increase `ds` by 1.333 to offset the SoC. This additional `1.333 ds` only decreases the total cost by 0.4 whereas the `1 cs` has a total cost of 0.5, meaning there was net gain of 0.1. This can be repeated infinitely, leading to the unbounded result. If `ds`'s SoC was slightly lower, say -1.2, then the result will be finite:
```typescript
{ status: 'optimal', result: 1.25, variables: [ [ 'cs', 2.5 ] ] }
```
